name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Dump label info
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
