name: deploy

on:
  push:
    branches:
      - main
    tags:

jobs:
  deploy-dev:
    name: Dump label info
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  deploy-staging:
    name: Dump label info
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  deploy-prod:
    name: Dump label info
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
